### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by SDFI** [smartsheet-platform/backup-java#11]
Is there any way to configure the tool to populate the backup data while preventing the file time stamps from being updated to the time the backup was created?  I'm trying to find a way to keep as much original FS metadata intact as possible.

**Comment by avioing** [comment]
The backup tool doesn't do that today, but you are certainly welcome to
modify it in any way you want, including managing file time stamps to fit
your needs.

**Comment by SDFI** [comment]
Unfortunately, I don't know much about coding.  I wouldn't even know if its a matter of changing some of the existing code or if I would have to construct a whole new module....or even if either of those is on the right track at all.

**Comment by avioing** [comment]
If this is a critical need for you, there may be another way.  Since we
don't have your direct contact information, can you please reach out to us
at api@smartsheet.com and we can take it from there.  Tx
